language: node_js
node_js:
- '10'
cache: yarn
install: yarn install --frozen-lockfile
stages:
- name: test
- name: deploy
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script:
    - yarn build:dev
    before_deploy:
    - export RELEASE_TAG=$(jq .version package.json | tr -d \" | cut -d . -f "1")
    deploy:
    - provider: s3
      bucket: auth-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
    - provider: s3
      bucket: auth${RELEASE_TAG}-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
notifications:
  slack:
    secure: rqkeIduFhSRzCDWVbnEgVVgq9+94ZknecoygmyoY5el2LKHtHPJuUU0gMB9zjPhsvvi3fOlaKKGX60PjGSMI19/LEAGMe2rYsgWbArU3/IysUqCtziF2dyTfgJFkTu5CZDkQzwdG3VPForKxmYg3RfZd46Sscf5RET8E1GUKHQqfk5eWmSTCYqpK3gkJdFyz8q5auFHiXQpEt1nt55iUggkPCl9fAlB8bSAdXBQUeQUBBrH4kA5pY+0kaD7lvdm0C1ludAyPhXrsxhnfwxbEN2+oIs4aJQGs6oydmUl9CGdrzSXnQwmlbdiQ35jLYrPQrODiwDep7cC1Q7crGlM1iTyfCNan0p86AHQMD88zWMCSqIMoZLa0K4tDSaknoDtNThjRZfRbUt1DpniHuC7LxtbsbFJdqKppBSoNrEMauKBYnwTcomZm8VecMlN8+qvNaMpDLvZMvhUFSpS49qUHYP4Cww14CZJb362QEPe6HdfCnlGmfFmlDom6mdUNZzrC0wkbrHYHNsV0sK1K+MGujyvAVIRuKA2IV9i5uNxX6TjY+3yjGSt9e3X4Ja4Am2ne1kK8IZ59zOUdaO/tE5/y/ET1/v8tS5HJzq2CNlbGHHneDhwszPtDGah0GGNq3jd+e/fh/0W4CG9JcKYOsLo8FYrfmJ4pHpBXzjO8zty/xZk=
