language: node_js
node_js:
- '10'
env: RELEASE_TAG=v0.2
cache: yarn
install: yarn install --frozen-lockfile
stages:
- name: test
- name: deploy
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: deploy
    script:
    - yarn build:dev
    deploy:
    - provider: s3
      bucket: auth-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
    - provider: s3
      bucket: auth-dev.endpass.com
      region: us-east-1
      skip_cleanup: true
      local_dir: dist/app
      upload-dir: "$RELEASE_TAG"
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master$|^v[0-9]+\\.[0-9]+$"
notifications:
  slack:
    secure: QYgDUQcsAOFeSEQuK/FpiScPml9vLO8/SYjze2E2y64G/Rw8LEUGiMPuOZZy+AZbA2ryaELEYaTxk6HSPjqZJttNYJPfwt+9o38pwKwjyTQC5qKRCaJcyCfERUQJ2aLbmxnKKaWf9ZmA5C7li2pseI8+OnrYT9YgwYtdU9KRxlQ3DjhFLYwOkYEApbgHsSZ4Th8IWNCxpJTT6fVfkS27NkBldtAANTtb0hKqtDLPpKJz4slj2vSCaaLUaQjETsoAdiDoXdXZIPn33t0Aox4+nuY4Cnn2959q1N8e/dYzdWnSg/wDRRxiXbYpA9Ou4AddVVLpYiIGxsaYKIciukclIMTOioyUQKLSILXqFfM90rpU6zPMIkEHh4MVqb56oR9yNwKSKj+Uy9HOx5p9foB60mUqBjt7OwzUSXI/W7NMK8Fi6nCC4N8aFPJffnhXJwtVjUCjm87iKpmcWEWBxPNpMWvpL4ApQuJsrn+z0UP3GmCG4EFyHrrJ5+A/qV8WtAOp+Pt195778fqPE8NCOqtz28YFulalGZl/ES1koxJatUKOS1Lu/YduKorLdEp/zYVLdZYpGUzsfs23l0H0uTHBdBajTz+2NrUYfAHNOUkMSOVpqE3OjScwEZJ2vTdMM9tPvOlbc4f5+0fun49pAexPZHk2KuXrmB6eM/cqu90dvkY=
