language: node_js
node_js:
  - '10'
cache:
  directories:
  - "~/.cache"
install: yarn install --frozen-lockfile
script:
  - npm test && npm run build
stages:
  - test
  - name: deploy_npm
    if: branch = release
  - name: deploy_s3
    if: branch = master
jobs:
  include:
    - stage: deploy_npm
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
          npm run build && npm run semantic-release
          fi
    - stage: deploy_s3
      deploy:
        provider: s3
        access_key_id: "$ACCESS_KEY_ID"
        secret_access_key: "$SECRET_ACCESS_KEY"
        bucket: endpass-dev-test
        region: us-east-1
        skip_cleanup: true
        local_dir: dist/
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
